import requests
import feedparser
import json
from datetime import datetime
from pathlib import Path

def get_hacker_news_top():
    """获取Hacker News Top 10"""
    try:
        response = requests.get('https://hacker-news.firebaseio.com/v0/topstories.json', timeout=30)
        top_ids = response.json()[:10]

        content = '## 🔥 Hacker News Top 10\n\n'

        for i, story_id in enumerate(top_ids, 1):
            story = requests.get(f'https://hacker-news.firebaseio.com/v0/item/{story_id}.json', timeout=10).json()
            title = story.get('title', 'No title')
            url = story.get('url', f'https://news.ycombinator.com/item?id={story_id}')
            score = story.get('score', 0)

            content += f'{i}. **[{title}]({url})** - {score} points\n'

        return content
    except Exception as e:
        print(f'Error fetching Hacker News: {e}')
        return '## 🔥 Hacker News Top 10\n\nFailed to fetch Hacker News.\n'


def get_arxiv_papers():
    """获取arXiv最新AI论文"""
    date = datetime.now()
    date_str = date.strftime('%Y-%m-%d')

    categories = ['cs.AI', 'cs.LG', 'cs.CL', 'cs.CV', 'cs.NE']
    category_query = ' OR '.join([f'cat:{cat}' for cat in categories])

    query = f'({category_query}) AND submittedDate:[{date_str} TO {date_str}]'

    try:
        url = f'http://export.arxiv.org/api/query?search_query={query}&start=0&max_results=5&sortBy=submittedDate&sortOrder=descending'
        response = requests.get(url, timeout=30)
        feed = feedparser.parse(response.text)

        content = f'\n## 📄 arXiv AI Papers - {date_str}\n\n'

        for i, entry in enumerate(feed.entries[:5], 1):
            title = entry.title.strip()
            paper_id = entry.id

            content += f'{i}. **[{title}]({paper_id})**\n'

        return content
    except Exception as e:
        print(f'Error fetching arxiv papers: {e}')
        return f'\n## 📄 arXiv AI Papers - {date_str}\n\nFailed to fetch papers.\n'


def get_github_trending():
    """获取GitHub Trending AI项目"""
    try:
        response = requests.get('https://gh-trending-api.herokuapp.com/repositories?language=python&since=daily', timeout=30)
        repos = response.json()[:5]

        content = '\n## ⭐ GitHub Trending AI Projects\n\n'

        for i, repo in enumerate(repos[:5], 1):
            name = repo.get('repositoryName', '')
            description = repo.get('description', '')[:100]
            url = repo.get('url', '')
            stars = repo.get('totalStars', 0)

            content += f'{i}. **[{name}]({url})** - {stars} stars\n'
            content += f'   {description}...\n\n'

        return content
    except Exception as e:
        print(f'Error fetching GitHub trending: {e}')
        return '\n## ⭐ GitHub Trending AI Projects\n\nFailed to fetch GitHub trending.\n'


def generate_digest():
    """生成每日AI进展摘要"""
    date_str = datetime.now().strftime('%Y-%m-%d')

    print(f'Generating AI Daily Digest for {date_str}...')

    digest = f'# 🤖 AI Daily Digest - {date_str}\n\n'
    digest += '---\n\n'

    digest += get_hacker_news_top()
    digest += get_arxiv_papers()
    digest += get_github_trending()

    digest += '\n---\n'
    digest += '*Generated by AI Daily Digest*\n'

    return digest


def save_digest(digest):
    """保存摘要到文件"""
    date_str = datetime.now().strftime('%Y-%m-%d')
    output_dir = Path(__file__).parent / 'digests'
    output_dir.mkdir(exist_ok=True)

    output_file = output_dir / f'ai-digest-{date_str}.md'

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(digest)

    print(f'Digest saved to: {output_file}')
    return output_file


if __name__ == '__main__':
    digest = generate_digest()
    print(digest)
    save_digest(digest)
