const axios = require('axios');
const xml2js = require('xml2js');
const fs = require('fs');
const path = require('path');

async function getHackerNewsTop() {
  console.log('Fetching Hacker News...');
  try {
    const response = await axios.get('https://hacker-news.firebaseio.com/v0/topstories.json');
    const topIds = response.data.slice(0, 10);

    let content = '## 🔥 Hacker News Top 10\n\n';

    for (let i = 0; i < topIds.length; i++) {
      const storyResponse = await axios.get(
        `https://hacker-news.firebaseio.com/v0/item/${topIds[i]}.json`
      );
      const story = storyResponse.data;
      const title = story.title || 'No title';
      const url = story.url || `https://news.ycombinator.com/item?id=${topIds[i]}`;
      const score = story.score || 0;

      content += `${i + 1}. **[${title}](${url})** - ${score} points\n`;
    }

    return content;
  } catch (error) {
    console.error('Error fetching Hacker News:', error.message);
    return '## 🔥 Hacker News Top 10\n\nFailed to fetch Hacker News.\n';
  }
}

async function getArxivPapers() {
  console.log('Fetching arXiv papers...');
  const today = new Date();
  const dateStr = today.toISOString().slice(0, 10);

  const categories = ['cs.AI', 'cs.LG', 'cs.CL', 'cs.CV', 'cs.NE'];
  const categoryQuery = categories.map(cat => `cat:${cat}`).join('+OR+');

  const query = `(${categoryQuery})`;

  try {
    const url = `http://export.arxiv.org/api/query?search_query=${query}&start=0&max_results=5&sortBy=submittedDate&sortOrder=descending`;
    const response = await axios.get(url);

    const parser = new xml2js.Parser();
    const result = await parser.parseStringPromise(response.data);
    const entries = result.feed.entry || [];

    let content = `\n## 📄 arXiv AI Papers - ${dateStr}\n\n`;

    entries.slice(0, 5).forEach((entry, i) => {
      const title = entry.title[0].trim();
      const paperId = entry.id[0];

      content += `${i + 1}. **[${title}](${paperId})**\n`;
    });

    return content;
  } catch (error) {
    console.error('Error fetching arXiv papers:', error.message);
    return `\n## 📄 arXiv AI Papers - ${dateStr}\n\nFailed to fetch papers.\n`;
  }
}

async function getGitHubTrending() {
  console.log('Fetching GitHub trending...');
  try {
    const response = await axios.get('https://gh-trending-api-production.up.railway.app/repositories?language=python&since=daily');
    const repos = response.data.slice(0, 5);

    let content = '\n## ⭐ GitHub Trending AI Projects\n\n';

    repos.forEach((repo, i) => {
      const name = repo.repositoryName || 'Unknown';
      const description = (repo.description || '').slice(0, 100);
      const url = `https://github.com/${name}`;
      const stars = repo.totalStars || 0;

      content += `${i + 1}. **[${name}](${url})** - ⭐ ${stars}\n`;
      if (description) {
        content += `   ${description}...\n`;
      }
      content += '\n';
    });

    return content;
  } catch (error) {
    console.error('Error fetching GitHub trending:', error.message);
    return '\n## ⭐ GitHub Trending AI Projects\n\nFailed to fetch GitHub trending.\n';
  }
}

async function generateDigest() {
  const dateStr = new Date().toISOString().slice(0, 10);

  console.log(`\n🤖 Generating AI Daily Digest for ${dateStr}...\n`);

  const hnContent = await getHackerNewsTop();
  const arxivContent = await getArxivPapers();
  const githubContent = await getGitHubTrending();

  let digest = `# 🤖 AI Daily Digest - ${dateStr}\n\n`;
  digest += '---\n\n';
  digest += hnContent;
  digest += arxivContent;
  digest += githubContent;
  digest += '\n---\n';
  digest += '*Generated by AI Daily Digest*\n';

  return digest;
}

function saveDigest(digest) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const outputDir = path.join(__dirname, 'digests');

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputFile = path.join(outputDir, `ai-digest-${dateStr}.md`);
  fs.writeFileSync(outputFile, digest, 'utf-8');
  console.log(`\n✅ Digest saved to: ${outputFile}`);
  return outputFile;
}

async function main() {
  try {
    const digest = await generateDigest();
    console.log('\n' + digest);
    saveDigest(digest);
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

main();
